# Generated by Django 4.2.4 on 2023-08-16 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bouquet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название букета')),
                ('price', models.IntegerField(verbose_name='Цена букета')),
                ('image', models.ImageField(upload_to='bouquet_image', verbose_name='Изображение букета')),
                ('desсription', models.TextField(verbose_name='Описание букета')),
                ('type', models.CharField(choices=[('на свадьбу', 'на свадьбу'), ('в школу', 'в школу'), ('без повода', 'без повода'), ('другой повод', 'другой повод')], default='без повода', max_length=50, verbose_name='Тип букета')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.IntegerField(verbose_name='ID пользователя')),
                ('username', models.CharField(max_length=200, verbose_name='Имя пользователя')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='Адресс заказа')),
                ('delivery_date', models.DateField(verbose_name='Дата доставки')),
                ('delivery_time', models.TimeField(verbose_name='Время доставки')),
                ('bouquet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='flowerapp.bouquet', verbose_name='Букет')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='flowerapp.client', verbose_name='Клиент')),
            ],
        ),
    ]
